name: localisationfutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20  # Assurez-vous que l'indentation est correcte
  http: ^1.0.0
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  image_picker: ^1.0.4
  flutter_tesseract_ocr: ^0.4.1
  google_maps_flutter: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/ambulance.jpg
    - assets/user.png
    - assets/hopital.jpg
    - assets/group_image.png
    - assets/medical.webp
    - assets/fire.jpg
    - assets/autres.png
    - assets/accident.jpg