services:
  patient-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: patient_service_db  # Changé ici
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
    ports:
      - "3306:3306"